sudo: false
dist: trusty
language: node_js
node_js:
  - '10'

before_install:
  - docker build -t rabbitmq:official-alpine-with-webstomp rabbitmq/
  - docker run -d --hostname rabbitmq --name rabbitmq -p 15674:15674 rabbitmq:official-alpine-with-webstomp

before_script:
  - docker exec rabbitmq rabbitmqctl status

script: ng test
